nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 0
    paths:
        '^/': null
